### ISSUE TITLE
Problem with "parent" being undefined with repeated forms

### ISSUE THREAD

**Issue by robertdempsey** [nmutalik/isolate-form#1]
Hi,

Handy little directive here. Just having an issue with the "parent" being undefined (line 17 of index.js). I have forms being repeated in an ng-repeat and they are, for some reason, loading twice. This results in the parent being undefined on the second time they are loaded.

I am not sure why they are being loaded twice, I have read that elements are sometimes loaded multiple times due to dirty checks and whatnot. But regardless, there may be need to be a check for undefined here for safety.

Cheers,
Rob

**Comment by nmutalik** [comment]
Hello. I am no longer supporting this repo. Feel free to fork, or since this a nearly 5 year old conversation, feel free to forget you ever wrote angular in the first place.
